name: Cypress Tests & Firebase hosting
'on':
  pull_request:
    types: [opened,synchronize]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # if: ${{ github.event.comment.body == 'Run cypress check'}}
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      - name: Configure Git Agent
        run: |
          git config --global user.email "nevetsGhost@sample.com"
          git config --global user.name "You are being haunted!!"
          
      - name: Set Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Branch info
        run: |
          echo "Branch ->"
          git status
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          build: yarn build
          start: yarn serve
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          
      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
          # we have already installed everything
          install: false
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - run: npm i && npm run build
      
      - id: firebase_webs
        name: Host to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIP_PROJECTS }}'
          projectId: drip-projects
          
      - name: Display live URL
        shell: bash
        run: |
          echo "Web: ${{steps.firebase_webs.outputs.details_url}}"

