name: Cypress Tests & Firebase hosting
'on':
  issue_comment:
    types:
      - created

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'Run cypress check'}}
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
      - name: Configure Git Agent
        run: |
          git config --global user.email "nevetsGhost@sample.com"
          git config --global user.name "You are being haunted!!"
          
      - name: Branch info
        run: |
          echo "Branch "
          gh pr status
          git status
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          build: yarn build
          start: yarn serve
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      
      # upload reports to firebase
      - name: Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.AUTH_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIP_PROJECTS }}'
          channelId: live
          projectId: drip-projects
        env:
          VUE_APP_TEST: ${{ secrets.MY_ENV }}
          
      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
          # we have already installed everything
          install: false
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      # report machine parameters
      - run: yarn cypress info
      - run: node -p 'os.cpus()'

