name: Run Component tests
on:
  issue_comment:
    types: [created]

jobs:
  mini-run:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Run component tests'
    steps:
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.sha.outputs.result }}
      
      - name: Configure Git Agent
        run: |
          git config --global user.email "nevetsGhost@sample.com"
          git config --global user.name "You are being haunted!!"
          
      - name: Branch info
        run: |
          echo "Branch:"
          git status
      
      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
