name: Run Action on Comment

on:
  issue_comment:
    types:
      - created

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'Roll Comment Dice'}}
    steps:
      - name: Pass randomly
        run: |
          exit $((RANDOM % 2))
      - name: Message success
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Comment Created! ✅',
            });
            
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Comment failed! ❌',
            });  
