name: Approved PR
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.sha.outputs.result }}
      
      - name: Configure Git Agent
        run: |
          git config --global user.email "nevetsGhost@sample.com"
          git config --global user.name "You are being haunted!!"
          
      - name: Fetch Branch Name
        run: |
          echo "Branch:"
          git status
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          build: yarn build
          start: yarn serve
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Comment
        if: steps.find-last-comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: "All test cases are passed!! Merge it carefully to master!!."
